import type { Metadata } from "next";
import "./globals.css";
import { Asap } from "next/font/google";
import { AuthProvider } from "../context/contextAuth"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const asap = Asap({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={asap.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
